version: '2'
services:
  node:
    command: /bin/sh -c "npm run setup && npm start"
    image: node
    working_dir: /opt
    volumes:
     - .:/opt
     - /opt/node_modules
     - /opt/typings
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      TERM: dumb
